version: '3.7'

services:
  web:
    image: nginx:latest
    restart: always
    expose:
      - 80
    environment:
      - VIRTUAL_HOST=mvc.local.parallax.dev
      - CERT_NAME=local.parallax.dev
    volumes:
      - ./src:/src/:rw,cached
      - ./etc/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    env_file:
      - ./.env
    links:
      - php
      - db
  php:
    build: .
    restart: always
    expose:
      - 9000
    environment:
      - VIRTUAL_PORT=9000
      - VIRTUAL_PROTO=fastcgi
    volumes:
      - ./src:/src/:rw,cached
      - ./etc/php.ini:/usr/local/etc/php/conf.d/00_mvc.ini:ro
    env_file:
      - ./.env
    depends_on:
      - db
  worker:
    build: .
    restart: always
    volumes:
      - ./src:/src/:rw,cached
      - ./etc/php.ini:/usr/local/etc/php/conf.d/00_worker.ini:ro
    env_file:
      - ./.env
    command: php command Queue work
    depends_on:
      - db
  db:
    image: mysql:5.6.41
    volumes:
      - db-data:/var/lib/mysql/data
    env_file:
      - ./.env
volumes:
  db-data:
  app-sync:
    external: true
networks:
  default:
    external:
      name: parallax-proxy