version: '3.7'

services:
  web:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    links:
      - "php"
      - "db"
    env_file:
      - "./.env"
    volumes:
      - ./src:/src/:rw,delegated
      - ./etc/nginx.conf:/etc/nginx/conf.d/default.conf:ro
  php:
    build: .
    restart: always
    ports:
      - 9000:9000
    volumes:
      - app-sync:/src/:nocopy
      - ./etc/php.ini:/usr/local/etc/php/conf.d/00_mvc.ini:ro
    env_file:
      - "./.env"
    depends_on:
      - db
  worker:
    build: .
    restart: always
    volumes:
      - app-sync:/src/:nocopy
      - ./etc/php.ini:/usr/local/etc/php/conf.d/00_worker.ini:ro
    env_file:
      - "./.env"
    command: php command Queue work
    depends_on:
      - db
  db:
    image: mysql:5.6.41
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql/data
    env_file:
      - "./.env"
volumes:
  db-data:
  app-sync:
    external: true
